### ISSUE TITLE
地物マスタの取得方法を一本化して集約したい。

### ISSUE THREAD

**Issue by matobaa** [hinamei/Study-Map#13]
バリエーションが増えてきた。

| 実装方法 | PROs | CONs |
|----------|-----|-----|
| geojsonファイル | 実装がらく。実行時に高速。 | 変更するのに開発者ロールが必要、変更したら再リリースが必要。
| geojson@firestore | 実行時に高速。 | とりいそぎ実装しただけ。保守性がよくない。検索フィルタかけられない
| geopoint@firestore | 実行時に高速。<br>検索フィルタかけられる。 | 保守性がよくない。
| Spreadsheet | 保守がらく | 検索フィルタかけられない、なんか遅そう

geopoint にしたい。保守性が悪いのをどうにかしたい。

**Comment by mymg5832** [comment]
Geopointで進める！（決定）
