### ISSUE TITLE
バグ: 地図座標が表示のたびに仙台周辺に戻ってしまう。

### ISSUE THREAD

**Issue by matobaa** [hinamei/Study-Map#15]
地図画面、詳細画面、一覧画面のうち、地図画面の初期表示時に仙台周辺に設定しているが、
地図画面で適当な場所に移動したあと、詳細・一覧画面から地図画面に戻った時にまた仙台周辺に戻ってしまう。

mounted で設定するのではなく、もうすこし早いタイミングで設定するか、初期座標をVueコンポネントのdataの初期データとしておけばよいのではないか。

**Comment by asahina820** [comment]
GISあるあるなんですよね・・
地図を移動するたびに中心座標を保持して、sessionStorageに格納しておき、画面遷移時に保持した中心座標をセットする、という方法を見つけました。
https://qiita.com/akira-yp/items/cf603d0a6fe99521f57f

**Comment by matobaa** [comment]
参考URLありがとうございます! 修正してみました。
