### ISSUE TITLE
UI改善

### ISSUE THREAD

**Issue by asahina820** [hinamei/Study-Map#17]
ぱんださんからカラースキームもらったらヘッダーに反映する
レイアウト調整

**Comment by asahina820** [comment]
ぱんださんからもらったカラースキーム　ピンク(D70087)
https://paletton.com/#uid=5571n0k-lE1MHvMVrrjjXMHpoF3

**Comment by asahina820** [comment]
ヘッダーは完了。

**Comment by asahina820** [comment]
詳細画面も画像がでかすぎて見づらいのを直したい。

**Comment by asahina820** [comment]
スマホだとヘッダーのレイアウトが崩れる。詳細画面が見づらい。
レスポンシブ対応必須。

**Comment by matobaa** [comment]
レスポンシブ対応、なにかプランはありますか？

- 現在のSemantic-UIベースで、がんばってレスポンシブなcssを書く。
- レスポンシブなCSSフレームワークに乗り換える。Bulma, vuetify, Quasar, ant-design など

**Comment by asahina820** [comment]
いったん現行のCSSフレームワークで、レスポンシブ対応する方向でいきます。
