### ISSUE TITLE
ファビコン小さすぎて全然見えない

### ISSUE THREAD

**Issue by matobaa** [hinamei/Study-Map#25]

**Comment by asahina820** [comment]
しまねさん
上のアイコンだけにすると話したと思うので、編集お願いします！

**Comment by hinamei** [comment]
しまねさん
上のアイコンだけにすると話したと思うので、編集お願いします！

**Comment by matobaa** [comment]
PWA用にどれくらいサイズを用意すればいいんだろう……。
https://developer.mozilla.org/ja/docs/Web/Manifest/icons
だと、48x48 と 72x72 96x96 128x128 256x256 の2種類のようです。

**Comment by matobaa** [comment]
https://stackoverflow.com/a/52322368 によれば、

android用に
- icon-72x72
- icon-96x96
- icon-128x128
- icon-144x144
- icon-152x152
- icon-192x192
- icon-384x384
- icon-512x512

iOS用に
- icon-120x120
- icon-180x180

https://webty.jp/staffblog/production/post-696/ によれば、
- 180×180 (apple touch icon)
- 192×192 (android install banner)
- 512×512 (Splash screen)

**Comment by matobaa** [comment]
とりあえずファビコン以外は優先度低です

**Comment by mymg5832** [comment]
faviconと以下のピクセル数の画像を本日中にpushします！おまちください
180×180 (apple touch icon)
192×192 (android install banner)
512×512 (Splash screen)
