### ISSUE TITLE
チュートリアル画面を作成する

### ISSUE THREAD

**Issue by asahina820** [hinamei/Study-Map#27]

**Comment by asahina820** [comment]
intro.js（https://introjs.com/ ）をみつけた。
さくっとチュートリアルを作れそう。

**Comment by asahina820** [comment]
↑非商用であれば、無償で利用可能。

**Comment by matobaa** [comment]
closed by #28

**Comment by matobaa** [comment]
- Session Cookie になっているのでブラウザ閉じたらまた登場してしまう。Expires が必要?
- Path の指定方法がなんかおかしい。セミコロンが必要?
![image](https://user-images.githubusercontent.com/87034/166716586-ce43acfc-1a75-49b9-9c0a-39b222c9420e.png)

**Comment by asahina820** [comment]
Cookieはいったん適当に実装してしまったので、不十分でしたね・・
後日対応します！
