### ISSUE TITLE
Firebase Hostingで公開用のディレクトリ検討

### ISSUE THREAD

**Issue by asahina820** [hinamei/Study-Map#48]
Firebase Hostingで公開用のディレクトリを指定する。
そのため、GitHubのこのリポジトリに、公開用のディレクトリを作成する必要がある。
https://firebase.google.com/docs/hosting/quickstart?hl=ja

ReactやVue製のアプリケーションだとビルド用のディレクトリ(build, distなど)を指定するらしいが
現在はビルドしていないためビルド用のディレクトリはない。

案は以下の通り。
1.  公開用のディレクトリを作って、現在のファイルたちをそちらに移行する
2.  ビルド用のディレクトリを作って、現在のファイルたちをビルドしてビルド用ディレクトリに格納する

**Comment by matobaa** [comment]
参考: https://firebase.google.com/docs/hosting/github-integration を読んでいます。
どっちが好みかといえば、私は案2です。

このまま機能フリーズする前提であれば、現在のルートをそのまま公開するのでもよさそうです。
以下のスクリプトそのままでいいのでは。
https://github.com/marketplace/actions/deploy-to-firebase-hosting#deploy-to-your-live-channel-on-merge
∵ いまリポジトリルートにあってアプリ対象じゃないのってREADME.md, geojson/*, .vscode/* くらいで、一緒にデプロイしても害はなさそうなので。

あるいは、今後ESM化やVue3化する前提で、
とりあえずのビルドスクリプトとして、まるっとdistにコピーする Github Actions Job を書いてやればよさそう。
[understanding-github-actions](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions?learn=getting_started&learnProduct=actions#:~:text=The%20run%20keyword) を参考に、まずは
 `- run: mkdir dist; cp -r img *.{html,js,css,vue} dist/` みたいにシェルコマンドをそのまま羅列しとけばよいかと。
∵ 将来的に package.json とかを作り始めた段階で、そのシェルコマンドを `run: npm build` などに置き換える想定です。

念のためですが、dist は git addせず、.gitignore に `dist/*` を追加する、で認識合いますか?
